name: Deploy to Server on Push

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # 配置服务器的 SSH 私钥
          name: id_ed25519                       # Name of the key file
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}  # Add known_hosts
          if_key_exists: fail

      - name: Deploy via SSH
        run: |
          ssh -i /home/runner/.ssh/id_ed25519 \
              tug@213.35.119.238 -p 2200 \
              "cd ~/StrikeAPose && \
               git stash && git pull origin main && git stash apply && \
            #    docker compose down && \
            #    docker compose up -d --build && \
               echo 'Deployment completed successfully.'"  # 如果使用 Docker